# Permalinks
permalink: "/:title.html"

# Setup
title:            saif's website
repository:       0xsirsaif/0xsirsaif.github.io
url:              https://0xsirsaif.github.io/
baseurl:          ""
description:      "Notes on software engineering, databases, and systems programming"
author:
  name:           "Saif"

encoding: utf-8

exclude:
  - "drafts"
  - "*.log"
  - ".bundle"
  - "vendor"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: main
  -
    scope:
      path: "notes"
      type: "posts"
    values:
      layout: "post"
      author: "0xsaif"
  -
    scope:
      path: "etc"
      type: "pages"
    values:
      layout: main
  -
    scope:
      path: "bookmarks"
      type: "pages"
    values:
      layout: main

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..4

sass:
    sass_dir: _sass
    style: compressed

# Navigation
nav:
  - name:           "notes"
    href:           "/notes"
    kind:           "dir"
  - name:           "bookmarks"
    href:           "/bookmarks"
    kind:           "dir"
  - name:           "about.md"
    href:           "/"
    kind:           "file"
  - name:           "résumé.pdf"
    href:           "/Mohamed_Saif_Resume.pdf"
    kind:           "file"
